@api_HostAddress = http://localhost:5098

POST {{api_HostAddress}}/placeBet/
Accept: application/json

POST {{api_HostAddress}}/spin/
Accept: application/json

Get {{api_HostAddress}}/showPreviousSpins/
Accept: application/json

POST {{api_HostAddress}}/payout/
Accept: application/json

###
